// Code generated by gen.py. DO NOT EDIT.
package esphomeproto

//go:generate ./testdata/setup.sh gen/gen.py

const (
	ESPHOME_VERSION = "29.0.0"
)

var MessageTypeToType = map[int]MessageFactory{
	1:   messageFactory[HelloRequest](),
	2:   messageFactory[HelloResponse](),
	3:   messageFactory[ConnectRequest](),
	4:   messageFactory[ConnectResponse](),
	5:   messageFactory[DisconnectRequest](),
	6:   messageFactory[DisconnectResponse](),
	7:   messageFactory[PingRequest](),
	8:   messageFactory[PingResponse](),
	9:   messageFactory[DeviceInfoRequest](),
	10:  messageFactory[DeviceInfoResponse](),
	11:  messageFactory[ListEntitiesRequest](),
	12:  messageFactory[ListEntitiesBinarySensorResponse](),
	13:  messageFactory[ListEntitiesCoverResponse](),
	14:  messageFactory[ListEntitiesFanResponse](),
	15:  messageFactory[ListEntitiesLightResponse](),
	16:  messageFactory[ListEntitiesSensorResponse](),
	17:  messageFactory[ListEntitiesSwitchResponse](),
	18:  messageFactory[ListEntitiesTextSensorResponse](),
	19:  messageFactory[ListEntitiesDoneResponse](),
	20:  messageFactory[SubscribeStatesRequest](),
	21:  messageFactory[BinarySensorStateResponse](),
	22:  messageFactory[CoverStateResponse](),
	23:  messageFactory[FanStateResponse](),
	24:  messageFactory[LightStateResponse](),
	25:  messageFactory[SensorStateResponse](),
	26:  messageFactory[SwitchStateResponse](),
	27:  messageFactory[TextSensorStateResponse](),
	28:  messageFactory[SubscribeLogsRequest](),
	29:  messageFactory[SubscribeLogsResponse](),
	30:  messageFactory[CoverCommandRequest](),
	31:  messageFactory[FanCommandRequest](),
	32:  messageFactory[LightCommandRequest](),
	33:  messageFactory[SwitchCommandRequest](),
	34:  messageFactory[SubscribeHomeassistantServicesRequest](),
	35:  messageFactory[HomeassistantServiceResponse](),
	36:  messageFactory[GetTimeRequest](),
	37:  messageFactory[GetTimeResponse](),
	38:  messageFactory[SubscribeHomeAssistantStatesRequest](),
	39:  messageFactory[SubscribeHomeAssistantStateResponse](),
	40:  messageFactory[HomeAssistantStateResponse](),
	41:  messageFactory[ListEntitiesServicesResponse](),
	42:  messageFactory[ExecuteServiceRequest](),
	43:  messageFactory[ListEntitiesCameraResponse](),
	44:  messageFactory[CameraImageResponse](),
	45:  messageFactory[CameraImageRequest](),
	46:  messageFactory[ListEntitiesClimateResponse](),
	47:  messageFactory[ClimateStateResponse](),
	48:  messageFactory[ClimateCommandRequest](),
	49:  messageFactory[ListEntitiesNumberResponse](),
	50:  messageFactory[NumberStateResponse](),
	51:  messageFactory[NumberCommandRequest](),
	52:  messageFactory[ListEntitiesSelectResponse](),
	53:  messageFactory[SelectStateResponse](),
	54:  messageFactory[SelectCommandRequest](),
	55:  messageFactory[ListEntitiesSirenResponse](),
	56:  messageFactory[SirenStateResponse](),
	57:  messageFactory[SirenCommandRequest](),
	58:  messageFactory[ListEntitiesLockResponse](),
	59:  messageFactory[LockStateResponse](),
	60:  messageFactory[LockCommandRequest](),
	61:  messageFactory[ListEntitiesButtonResponse](),
	62:  messageFactory[ButtonCommandRequest](),
	63:  messageFactory[ListEntitiesMediaPlayerResponse](),
	64:  messageFactory[MediaPlayerStateResponse](),
	65:  messageFactory[MediaPlayerCommandRequest](),
	66:  messageFactory[SubscribeBluetoothLEAdvertisementsRequest](),
	67:  messageFactory[BluetoothLEAdvertisementResponse](),
	68:  messageFactory[BluetoothDeviceRequest](),
	69:  messageFactory[BluetoothDeviceConnectionResponse](),
	70:  messageFactory[BluetoothGATTGetServicesRequest](),
	71:  messageFactory[BluetoothGATTGetServicesResponse](),
	72:  messageFactory[BluetoothGATTGetServicesDoneResponse](),
	73:  messageFactory[BluetoothGATTReadRequest](),
	74:  messageFactory[BluetoothGATTReadResponse](),
	75:  messageFactory[BluetoothGATTWriteRequest](),
	76:  messageFactory[BluetoothGATTReadDescriptorRequest](),
	77:  messageFactory[BluetoothGATTWriteDescriptorRequest](),
	78:  messageFactory[BluetoothGATTNotifyRequest](),
	79:  messageFactory[BluetoothGATTNotifyDataResponse](),
	80:  messageFactory[SubscribeBluetoothConnectionsFreeRequest](),
	81:  messageFactory[BluetoothConnectionsFreeResponse](),
	82:  messageFactory[BluetoothGATTErrorResponse](),
	83:  messageFactory[BluetoothGATTWriteResponse](),
	84:  messageFactory[BluetoothGATTNotifyResponse](),
	85:  messageFactory[BluetoothDevicePairingResponse](),
	86:  messageFactory[BluetoothDeviceUnpairingResponse](),
	87:  messageFactory[UnsubscribeBluetoothLEAdvertisementsRequest](),
	88:  messageFactory[BluetoothDeviceClearCacheResponse](),
	89:  messageFactory[SubscribeVoiceAssistantRequest](),
	90:  messageFactory[VoiceAssistantRequest](),
	91:  messageFactory[VoiceAssistantResponse](),
	92:  messageFactory[VoiceAssistantEventResponse](),
	93:  messageFactory[BluetoothLERawAdvertisementsResponse](),
	94:  messageFactory[ListEntitiesAlarmControlPanelResponse](),
	95:  messageFactory[AlarmControlPanelStateResponse](),
	96:  messageFactory[AlarmControlPanelCommandRequest](),
	97:  messageFactory[ListEntitiesTextResponse](),
	98:  messageFactory[TextStateResponse](),
	99:  messageFactory[TextCommandRequest](),
	100: messageFactory[ListEntitiesDateResponse](),
	101: messageFactory[DateStateResponse](),
	102: messageFactory[DateCommandRequest](),
	103: messageFactory[ListEntitiesTimeResponse](),
	104: messageFactory[TimeStateResponse](),
	105: messageFactory[TimeCommandRequest](),
	106: messageFactory[VoiceAssistantAudio](),
	107: messageFactory[ListEntitiesEventResponse](),
	108: messageFactory[EventResponse](),
	109: messageFactory[ListEntitiesValveResponse](),
	110: messageFactory[ValveStateResponse](),
	111: messageFactory[ValveCommandRequest](),
	112: messageFactory[ListEntitiesDateTimeResponse](),
	113: messageFactory[DateTimeStateResponse](),
	114: messageFactory[DateTimeCommandRequest](),
	115: messageFactory[VoiceAssistantTimerEventResponse](),
	116: messageFactory[ListEntitiesUpdateResponse](),
	117: messageFactory[UpdateStateResponse](),
	118: messageFactory[UpdateCommandRequest](),
	119: messageFactory[VoiceAssistantAnnounceRequest](),
	120: messageFactory[VoiceAssistantAnnounceFinished](),
	121: messageFactory[VoiceAssistantConfigurationRequest](),
	122: messageFactory[VoiceAssistantConfigurationResponse](),
	123: messageFactory[VoiceAssistantSetConfiguration](),
}

func (x *HelloRequest) EsphomeMessageType() int      { return 1 }
func (x *HelloRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *HelloResponse) EsphomeMessageType() int      { return 2 }
func (x *HelloResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ConnectRequest) EsphomeMessageType() int      { return 3 }
func (x *ConnectRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ConnectResponse) EsphomeMessageType() int      { return 4 }
func (x *ConnectResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *DisconnectRequest) EsphomeMessageType() int      { return 5 }
func (x *DisconnectRequest) EsphomeSource() APISourceType { return APISourceType(0) }

func (x *DisconnectResponse) EsphomeMessageType() int      { return 6 }
func (x *DisconnectResponse) EsphomeSource() APISourceType { return APISourceType(0) }

func (x *PingRequest) EsphomeMessageType() int      { return 7 }
func (x *PingRequest) EsphomeSource() APISourceType { return APISourceType(0) }

func (x *PingResponse) EsphomeMessageType() int      { return 8 }
func (x *PingResponse) EsphomeSource() APISourceType { return APISourceType(0) }

func (x *DeviceInfoRequest) EsphomeMessageType() int      { return 9 }
func (x *DeviceInfoRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *DeviceInfoResponse) EsphomeMessageType() int      { return 10 }
func (x *DeviceInfoResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ListEntitiesRequest) EsphomeMessageType() int      { return 11 }
func (x *ListEntitiesRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesBinarySensorResponse) EsphomeMessageType() int      { return 12 }
func (x *ListEntitiesBinarySensorResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ListEntitiesCoverResponse) EsphomeMessageType() int      { return 13 }
func (x *ListEntitiesCoverResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ListEntitiesFanResponse) EsphomeMessageType() int      { return 14 }
func (x *ListEntitiesFanResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ListEntitiesLightResponse) EsphomeMessageType() int      { return 15 }
func (x *ListEntitiesLightResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ListEntitiesSensorResponse) EsphomeMessageType() int      { return 16 }
func (x *ListEntitiesSensorResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ListEntitiesSwitchResponse) EsphomeMessageType() int      { return 17 }
func (x *ListEntitiesSwitchResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ListEntitiesTextSensorResponse) EsphomeMessageType() int      { return 18 }
func (x *ListEntitiesTextSensorResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ListEntitiesDoneResponse) EsphomeMessageType() int      { return 19 }
func (x *ListEntitiesDoneResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *SubscribeStatesRequest) EsphomeMessageType() int      { return 20 }
func (x *SubscribeStatesRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *BinarySensorStateResponse) EsphomeMessageType() int      { return 21 }
func (x *BinarySensorStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *CoverStateResponse) EsphomeMessageType() int      { return 22 }
func (x *CoverStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *FanStateResponse) EsphomeMessageType() int      { return 23 }
func (x *FanStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *LightStateResponse) EsphomeMessageType() int      { return 24 }
func (x *LightStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *SensorStateResponse) EsphomeMessageType() int      { return 25 }
func (x *SensorStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *SwitchStateResponse) EsphomeMessageType() int      { return 26 }
func (x *SwitchStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *TextSensorStateResponse) EsphomeMessageType() int      { return 27 }
func (x *TextSensorStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *SubscribeLogsRequest) EsphomeMessageType() int      { return 28 }
func (x *SubscribeLogsRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *SubscribeLogsResponse) EsphomeMessageType() int      { return 29 }
func (x *SubscribeLogsResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *CoverCommandRequest) EsphomeMessageType() int      { return 30 }
func (x *CoverCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *FanCommandRequest) EsphomeMessageType() int      { return 31 }
func (x *FanCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *LightCommandRequest) EsphomeMessageType() int      { return 32 }
func (x *LightCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *SwitchCommandRequest) EsphomeMessageType() int      { return 33 }
func (x *SwitchCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *SubscribeHomeassistantServicesRequest) EsphomeMessageType() int { return 34 }
func (x *SubscribeHomeassistantServicesRequest) EsphomeSource() APISourceType {
	return APISourceType(2)
}

func (x *HomeassistantServiceResponse) EsphomeMessageType() int      { return 35 }
func (x *HomeassistantServiceResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *GetTimeRequest) EsphomeMessageType() int      { return 36 }
func (x *GetTimeRequest) EsphomeSource() APISourceType { return APISourceType(0) }

func (x *GetTimeResponse) EsphomeMessageType() int      { return 37 }
func (x *GetTimeResponse) EsphomeSource() APISourceType { return APISourceType(0) }

func (x *SubscribeHomeAssistantStatesRequest) EsphomeMessageType() int      { return 38 }
func (x *SubscribeHomeAssistantStatesRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *SubscribeHomeAssistantStateResponse) EsphomeMessageType() int      { return 39 }
func (x *SubscribeHomeAssistantStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *HomeAssistantStateResponse) EsphomeMessageType() int      { return 40 }
func (x *HomeAssistantStateResponse) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesServicesResponse) EsphomeMessageType() int      { return 41 }
func (x *ListEntitiesServicesResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ExecuteServiceRequest) EsphomeMessageType() int      { return 42 }
func (x *ExecuteServiceRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesCameraResponse) EsphomeMessageType() int      { return 43 }
func (x *ListEntitiesCameraResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *CameraImageResponse) EsphomeMessageType() int      { return 44 }
func (x *CameraImageResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *CameraImageRequest) EsphomeMessageType() int      { return 45 }
func (x *CameraImageRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesClimateResponse) EsphomeMessageType() int      { return 46 }
func (x *ListEntitiesClimateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ClimateStateResponse) EsphomeMessageType() int      { return 47 }
func (x *ClimateStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ClimateCommandRequest) EsphomeMessageType() int      { return 48 }
func (x *ClimateCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesNumberResponse) EsphomeMessageType() int      { return 49 }
func (x *ListEntitiesNumberResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *NumberStateResponse) EsphomeMessageType() int      { return 50 }
func (x *NumberStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *NumberCommandRequest) EsphomeMessageType() int      { return 51 }
func (x *NumberCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesSelectResponse) EsphomeMessageType() int      { return 52 }
func (x *ListEntitiesSelectResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *SelectStateResponse) EsphomeMessageType() int      { return 53 }
func (x *SelectStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *SelectCommandRequest) EsphomeMessageType() int      { return 54 }
func (x *SelectCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesSirenResponse) EsphomeMessageType() int      { return 55 }
func (x *ListEntitiesSirenResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *SirenStateResponse) EsphomeMessageType() int      { return 56 }
func (x *SirenStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *SirenCommandRequest) EsphomeMessageType() int      { return 57 }
func (x *SirenCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesLockResponse) EsphomeMessageType() int      { return 58 }
func (x *ListEntitiesLockResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *LockStateResponse) EsphomeMessageType() int      { return 59 }
func (x *LockStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *LockCommandRequest) EsphomeMessageType() int      { return 60 }
func (x *LockCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesButtonResponse) EsphomeMessageType() int      { return 61 }
func (x *ListEntitiesButtonResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ButtonCommandRequest) EsphomeMessageType() int      { return 62 }
func (x *ButtonCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesMediaPlayerResponse) EsphomeMessageType() int      { return 63 }
func (x *ListEntitiesMediaPlayerResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *MediaPlayerStateResponse) EsphomeMessageType() int      { return 64 }
func (x *MediaPlayerStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *MediaPlayerCommandRequest) EsphomeMessageType() int      { return 65 }
func (x *MediaPlayerCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *SubscribeBluetoothLEAdvertisementsRequest) EsphomeMessageType() int { return 66 }
func (x *SubscribeBluetoothLEAdvertisementsRequest) EsphomeSource() APISourceType {
	return APISourceType(2)
}

func (x *BluetoothLEAdvertisementResponse) EsphomeMessageType() int      { return 67 }
func (x *BluetoothLEAdvertisementResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *BluetoothDeviceRequest) EsphomeMessageType() int      { return 68 }
func (x *BluetoothDeviceRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *BluetoothDeviceConnectionResponse) EsphomeMessageType() int      { return 69 }
func (x *BluetoothDeviceConnectionResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *BluetoothGATTGetServicesRequest) EsphomeMessageType() int      { return 70 }
func (x *BluetoothGATTGetServicesRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *BluetoothGATTGetServicesResponse) EsphomeMessageType() int      { return 71 }
func (x *BluetoothGATTGetServicesResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *BluetoothGATTGetServicesDoneResponse) EsphomeMessageType() int      { return 72 }
func (x *BluetoothGATTGetServicesDoneResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *BluetoothGATTReadRequest) EsphomeMessageType() int      { return 73 }
func (x *BluetoothGATTReadRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *BluetoothGATTReadResponse) EsphomeMessageType() int      { return 74 }
func (x *BluetoothGATTReadResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *BluetoothGATTWriteRequest) EsphomeMessageType() int      { return 75 }
func (x *BluetoothGATTWriteRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *BluetoothGATTReadDescriptorRequest) EsphomeMessageType() int      { return 76 }
func (x *BluetoothGATTReadDescriptorRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *BluetoothGATTWriteDescriptorRequest) EsphomeMessageType() int      { return 77 }
func (x *BluetoothGATTWriteDescriptorRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *BluetoothGATTNotifyRequest) EsphomeMessageType() int      { return 78 }
func (x *BluetoothGATTNotifyRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *BluetoothGATTNotifyDataResponse) EsphomeMessageType() int      { return 79 }
func (x *BluetoothGATTNotifyDataResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *SubscribeBluetoothConnectionsFreeRequest) EsphomeMessageType() int { return 80 }
func (x *SubscribeBluetoothConnectionsFreeRequest) EsphomeSource() APISourceType {
	return APISourceType(2)
}

func (x *BluetoothConnectionsFreeResponse) EsphomeMessageType() int      { return 81 }
func (x *BluetoothConnectionsFreeResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *BluetoothGATTErrorResponse) EsphomeMessageType() int      { return 82 }
func (x *BluetoothGATTErrorResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *BluetoothGATTWriteResponse) EsphomeMessageType() int      { return 83 }
func (x *BluetoothGATTWriteResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *BluetoothGATTNotifyResponse) EsphomeMessageType() int      { return 84 }
func (x *BluetoothGATTNotifyResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *BluetoothDevicePairingResponse) EsphomeMessageType() int      { return 85 }
func (x *BluetoothDevicePairingResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *BluetoothDeviceUnpairingResponse) EsphomeMessageType() int      { return 86 }
func (x *BluetoothDeviceUnpairingResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *UnsubscribeBluetoothLEAdvertisementsRequest) EsphomeMessageType() int { return 87 }
func (x *UnsubscribeBluetoothLEAdvertisementsRequest) EsphomeSource() APISourceType {
	return APISourceType(2)
}

func (x *BluetoothDeviceClearCacheResponse) EsphomeMessageType() int      { return 88 }
func (x *BluetoothDeviceClearCacheResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *SubscribeVoiceAssistantRequest) EsphomeMessageType() int      { return 89 }
func (x *SubscribeVoiceAssistantRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *VoiceAssistantRequest) EsphomeMessageType() int      { return 90 }
func (x *VoiceAssistantRequest) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *VoiceAssistantResponse) EsphomeMessageType() int      { return 91 }
func (x *VoiceAssistantResponse) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *VoiceAssistantEventResponse) EsphomeMessageType() int      { return 92 }
func (x *VoiceAssistantEventResponse) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *BluetoothLERawAdvertisementsResponse) EsphomeMessageType() int      { return 93 }
func (x *BluetoothLERawAdvertisementsResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ListEntitiesAlarmControlPanelResponse) EsphomeMessageType() int { return 94 }
func (x *ListEntitiesAlarmControlPanelResponse) EsphomeSource() APISourceType {
	return APISourceType(1)
}

func (x *AlarmControlPanelStateResponse) EsphomeMessageType() int      { return 95 }
func (x *AlarmControlPanelStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *AlarmControlPanelCommandRequest) EsphomeMessageType() int      { return 96 }
func (x *AlarmControlPanelCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesTextResponse) EsphomeMessageType() int      { return 97 }
func (x *ListEntitiesTextResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *TextStateResponse) EsphomeMessageType() int      { return 98 }
func (x *TextStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *TextCommandRequest) EsphomeMessageType() int      { return 99 }
func (x *TextCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesDateResponse) EsphomeMessageType() int      { return 100 }
func (x *ListEntitiesDateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *DateStateResponse) EsphomeMessageType() int      { return 101 }
func (x *DateStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *DateCommandRequest) EsphomeMessageType() int      { return 102 }
func (x *DateCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesTimeResponse) EsphomeMessageType() int      { return 103 }
func (x *ListEntitiesTimeResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *TimeStateResponse) EsphomeMessageType() int      { return 104 }
func (x *TimeStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *TimeCommandRequest) EsphomeMessageType() int      { return 105 }
func (x *TimeCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *VoiceAssistantAudio) EsphomeMessageType() int      { return 106 }
func (x *VoiceAssistantAudio) EsphomeSource() APISourceType { return APISourceType(0) }

func (x *ListEntitiesEventResponse) EsphomeMessageType() int      { return 107 }
func (x *ListEntitiesEventResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *EventResponse) EsphomeMessageType() int      { return 108 }
func (x *EventResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ListEntitiesValveResponse) EsphomeMessageType() int      { return 109 }
func (x *ListEntitiesValveResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ValveStateResponse) EsphomeMessageType() int      { return 110 }
func (x *ValveStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *ValveCommandRequest) EsphomeMessageType() int      { return 111 }
func (x *ValveCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesDateTimeResponse) EsphomeMessageType() int      { return 112 }
func (x *ListEntitiesDateTimeResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *DateTimeStateResponse) EsphomeMessageType() int      { return 113 }
func (x *DateTimeStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *DateTimeCommandRequest) EsphomeMessageType() int      { return 114 }
func (x *DateTimeCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *VoiceAssistantTimerEventResponse) EsphomeMessageType() int      { return 115 }
func (x *VoiceAssistantTimerEventResponse) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *ListEntitiesUpdateResponse) EsphomeMessageType() int      { return 116 }
func (x *ListEntitiesUpdateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *UpdateStateResponse) EsphomeMessageType() int      { return 117 }
func (x *UpdateStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *UpdateCommandRequest) EsphomeMessageType() int      { return 118 }
func (x *UpdateCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *VoiceAssistantAnnounceRequest) EsphomeMessageType() int      { return 119 }
func (x *VoiceAssistantAnnounceRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *VoiceAssistantAnnounceFinished) EsphomeMessageType() int      { return 120 }
func (x *VoiceAssistantAnnounceFinished) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *VoiceAssistantConfigurationRequest) EsphomeMessageType() int      { return 121 }
func (x *VoiceAssistantConfigurationRequest) EsphomeSource() APISourceType { return APISourceType(2) }

func (x *VoiceAssistantConfigurationResponse) EsphomeMessageType() int      { return 122 }
func (x *VoiceAssistantConfigurationResponse) EsphomeSource() APISourceType { return APISourceType(1) }

func (x *VoiceAssistantSetConfiguration) EsphomeMessageType() int      { return 123 }
func (x *VoiceAssistantSetConfiguration) EsphomeSource() APISourceType { return APISourceType(2) }
