// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package entity

import (
	"errors"
	"fmt"
)

const (
	// AlarmControlPanelStateDisarmed is a AlarmControlPanelState of type Disarmed.
	AlarmControlPanelStateDisarmed AlarmControlPanelState = iota
	// AlarmControlPanelStateArmedHome is a AlarmControlPanelState of type Armed_home.
	AlarmControlPanelStateArmedHome
	// AlarmControlPanelStateArmedAway is a AlarmControlPanelState of type Armed_away.
	AlarmControlPanelStateArmedAway
	// AlarmControlPanelStateArmedNight is a AlarmControlPanelState of type Armed_night.
	AlarmControlPanelStateArmedNight
	// AlarmControlPanelStateArmedVacation is a AlarmControlPanelState of type Armed_vacation.
	AlarmControlPanelStateArmedVacation
	// AlarmControlPanelStateArmedCustomBypass is a AlarmControlPanelState of type Armed_custom_bypass.
	AlarmControlPanelStateArmedCustomBypass
	// AlarmControlPanelStatePending is a AlarmControlPanelState of type Pending.
	AlarmControlPanelStatePending
	// AlarmControlPanelStateArming is a AlarmControlPanelState of type Arming.
	AlarmControlPanelStateArming
	// AlarmControlPanelStateDisarming is a AlarmControlPanelState of type Disarming.
	AlarmControlPanelStateDisarming
	// AlarmControlPanelStateTriggered is a AlarmControlPanelState of type Triggered.
	AlarmControlPanelStateTriggered
)

var ErrInvalidAlarmControlPanelState = errors.New("not a valid AlarmControlPanelState")

const _AlarmControlPanelStateName = "disarmedarmed_homearmed_awayarmed_nightarmed_vacationarmed_custom_bypasspendingarmingdisarmingtriggered"

var _AlarmControlPanelStateMap = map[AlarmControlPanelState]string{
	AlarmControlPanelStateDisarmed:          _AlarmControlPanelStateName[0:8],
	AlarmControlPanelStateArmedHome:         _AlarmControlPanelStateName[8:18],
	AlarmControlPanelStateArmedAway:         _AlarmControlPanelStateName[18:28],
	AlarmControlPanelStateArmedNight:        _AlarmControlPanelStateName[28:39],
	AlarmControlPanelStateArmedVacation:     _AlarmControlPanelStateName[39:53],
	AlarmControlPanelStateArmedCustomBypass: _AlarmControlPanelStateName[53:72],
	AlarmControlPanelStatePending:           _AlarmControlPanelStateName[72:79],
	AlarmControlPanelStateArming:            _AlarmControlPanelStateName[79:85],
	AlarmControlPanelStateDisarming:         _AlarmControlPanelStateName[85:94],
	AlarmControlPanelStateTriggered:         _AlarmControlPanelStateName[94:103],
}

// String implements the Stringer interface.
func (x AlarmControlPanelState) String() string {
	if str, ok := _AlarmControlPanelStateMap[x]; ok {
		return str
	}
	return fmt.Sprintf("AlarmControlPanelState(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AlarmControlPanelState) IsValid() bool {
	_, ok := _AlarmControlPanelStateMap[x]
	return ok
}

var _AlarmControlPanelStateValue = map[string]AlarmControlPanelState{
	_AlarmControlPanelStateName[0:8]:    AlarmControlPanelStateDisarmed,
	_AlarmControlPanelStateName[8:18]:   AlarmControlPanelStateArmedHome,
	_AlarmControlPanelStateName[18:28]:  AlarmControlPanelStateArmedAway,
	_AlarmControlPanelStateName[28:39]:  AlarmControlPanelStateArmedNight,
	_AlarmControlPanelStateName[39:53]:  AlarmControlPanelStateArmedVacation,
	_AlarmControlPanelStateName[53:72]:  AlarmControlPanelStateArmedCustomBypass,
	_AlarmControlPanelStateName[72:79]:  AlarmControlPanelStatePending,
	_AlarmControlPanelStateName[79:85]:  AlarmControlPanelStateArming,
	_AlarmControlPanelStateName[85:94]:  AlarmControlPanelStateDisarming,
	_AlarmControlPanelStateName[94:103]: AlarmControlPanelStateTriggered,
}

// ParseAlarmControlPanelState attempts to convert a string to a AlarmControlPanelState.
func ParseAlarmControlPanelState(name string) (AlarmControlPanelState, error) {
	if x, ok := _AlarmControlPanelStateValue[name]; ok {
		return x, nil
	}
	return AlarmControlPanelState(0), fmt.Errorf("%s is %w", name, ErrInvalidAlarmControlPanelState)
}

const (
	// ClimateActionOff is a ClimateAction of type Off.
	ClimateActionOff ClimateAction = iota
	// ClimateActionCooling is a ClimateAction of type Cooling.
	ClimateActionCooling
	// ClimateActionHeating is a ClimateAction of type Heating.
	ClimateActionHeating
	// ClimateActionIdle is a ClimateAction of type Idle.
	ClimateActionIdle
	// ClimateActionDrying is a ClimateAction of type Drying.
	ClimateActionDrying
	// ClimateActionFan is a ClimateAction of type Fan.
	ClimateActionFan
)

var ErrInvalidClimateAction = errors.New("not a valid ClimateAction")

const _ClimateActionName = "offcoolingheatingidledryingfan"

var _ClimateActionMap = map[ClimateAction]string{
	ClimateActionOff:     _ClimateActionName[0:3],
	ClimateActionCooling: _ClimateActionName[3:10],
	ClimateActionHeating: _ClimateActionName[10:17],
	ClimateActionIdle:    _ClimateActionName[17:21],
	ClimateActionDrying:  _ClimateActionName[21:27],
	ClimateActionFan:     _ClimateActionName[27:30],
}

// String implements the Stringer interface.
func (x ClimateAction) String() string {
	if str, ok := _ClimateActionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ClimateAction(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClimateAction) IsValid() bool {
	_, ok := _ClimateActionMap[x]
	return ok
}

var _ClimateActionValue = map[string]ClimateAction{
	_ClimateActionName[0:3]:   ClimateActionOff,
	_ClimateActionName[3:10]:  ClimateActionCooling,
	_ClimateActionName[10:17]: ClimateActionHeating,
	_ClimateActionName[17:21]: ClimateActionIdle,
	_ClimateActionName[21:27]: ClimateActionDrying,
	_ClimateActionName[27:30]: ClimateActionFan,
}

// ParseClimateAction attempts to convert a string to a ClimateAction.
func ParseClimateAction(name string) (ClimateAction, error) {
	if x, ok := _ClimateActionValue[name]; ok {
		return x, nil
	}
	return ClimateAction(0), fmt.Errorf("%s is %w", name, ErrInvalidClimateAction)
}

const (
	// ClimateFanModeOn is a ClimateFanMode of type On.
	ClimateFanModeOn ClimateFanMode = iota
	// ClimateFanModeOff is a ClimateFanMode of type Off.
	ClimateFanModeOff
	// ClimateFanModeAuto is a ClimateFanMode of type Auto.
	ClimateFanModeAuto
	// ClimateFanModeLow is a ClimateFanMode of type Low.
	ClimateFanModeLow
	// ClimateFanModeMedium is a ClimateFanMode of type Medium.
	ClimateFanModeMedium
	// ClimateFanModeHigh is a ClimateFanMode of type High.
	ClimateFanModeHigh
	// ClimateFanModeMiddle is a ClimateFanMode of type Middle.
	ClimateFanModeMiddle
	// ClimateFanModeFocus is a ClimateFanMode of type Focus.
	ClimateFanModeFocus
	// ClimateFanModeDiffuse is a ClimateFanMode of type Diffuse.
	ClimateFanModeDiffuse
	// ClimateFanModeQuiet is a ClimateFanMode of type Quiet.
	ClimateFanModeQuiet
)

var ErrInvalidClimateFanMode = errors.New("not a valid ClimateFanMode")

const _ClimateFanModeName = "onoffautolowmediumhighmiddlefocusdiffusequiet"

var _ClimateFanModeMap = map[ClimateFanMode]string{
	ClimateFanModeOn:      _ClimateFanModeName[0:2],
	ClimateFanModeOff:     _ClimateFanModeName[2:5],
	ClimateFanModeAuto:    _ClimateFanModeName[5:9],
	ClimateFanModeLow:     _ClimateFanModeName[9:12],
	ClimateFanModeMedium:  _ClimateFanModeName[12:18],
	ClimateFanModeHigh:    _ClimateFanModeName[18:22],
	ClimateFanModeMiddle:  _ClimateFanModeName[22:28],
	ClimateFanModeFocus:   _ClimateFanModeName[28:33],
	ClimateFanModeDiffuse: _ClimateFanModeName[33:40],
	ClimateFanModeQuiet:   _ClimateFanModeName[40:45],
}

// String implements the Stringer interface.
func (x ClimateFanMode) String() string {
	if str, ok := _ClimateFanModeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ClimateFanMode(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClimateFanMode) IsValid() bool {
	_, ok := _ClimateFanModeMap[x]
	return ok
}

var _ClimateFanModeValue = map[string]ClimateFanMode{
	_ClimateFanModeName[0:2]:   ClimateFanModeOn,
	_ClimateFanModeName[2:5]:   ClimateFanModeOff,
	_ClimateFanModeName[5:9]:   ClimateFanModeAuto,
	_ClimateFanModeName[9:12]:  ClimateFanModeLow,
	_ClimateFanModeName[12:18]: ClimateFanModeMedium,
	_ClimateFanModeName[18:22]: ClimateFanModeHigh,
	_ClimateFanModeName[22:28]: ClimateFanModeMiddle,
	_ClimateFanModeName[28:33]: ClimateFanModeFocus,
	_ClimateFanModeName[33:40]: ClimateFanModeDiffuse,
	_ClimateFanModeName[40:45]: ClimateFanModeQuiet,
}

// ParseClimateFanMode attempts to convert a string to a ClimateFanMode.
func ParseClimateFanMode(name string) (ClimateFanMode, error) {
	if x, ok := _ClimateFanModeValue[name]; ok {
		return x, nil
	}
	return ClimateFanMode(0), fmt.Errorf("%s is %w", name, ErrInvalidClimateFanMode)
}

const (
	// ClimateModeOff is a ClimateMode of type Off.
	ClimateModeOff ClimateMode = iota
	// ClimateModeHeatCool is a ClimateMode of type Heat_cool.
	ClimateModeHeatCool
	// ClimateModeCool is a ClimateMode of type Cool.
	ClimateModeCool
	// ClimateModeHeat is a ClimateMode of type Heat.
	ClimateModeHeat
	// ClimateModeFanOnly is a ClimateMode of type Fan_only.
	ClimateModeFanOnly
	// ClimateModeDry is a ClimateMode of type Dry.
	ClimateModeDry
	// ClimateModeAuto is a ClimateMode of type Auto.
	ClimateModeAuto
)

var ErrInvalidClimateMode = errors.New("not a valid ClimateMode")

const _ClimateModeName = "offheat_coolcoolheatfan_onlydryauto"

var _ClimateModeMap = map[ClimateMode]string{
	ClimateModeOff:      _ClimateModeName[0:3],
	ClimateModeHeatCool: _ClimateModeName[3:12],
	ClimateModeCool:     _ClimateModeName[12:16],
	ClimateModeHeat:     _ClimateModeName[16:20],
	ClimateModeFanOnly:  _ClimateModeName[20:28],
	ClimateModeDry:      _ClimateModeName[28:31],
	ClimateModeAuto:     _ClimateModeName[31:35],
}

// String implements the Stringer interface.
func (x ClimateMode) String() string {
	if str, ok := _ClimateModeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ClimateMode(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClimateMode) IsValid() bool {
	_, ok := _ClimateModeMap[x]
	return ok
}

var _ClimateModeValue = map[string]ClimateMode{
	_ClimateModeName[0:3]:   ClimateModeOff,
	_ClimateModeName[3:12]:  ClimateModeHeatCool,
	_ClimateModeName[12:16]: ClimateModeCool,
	_ClimateModeName[16:20]: ClimateModeHeat,
	_ClimateModeName[20:28]: ClimateModeFanOnly,
	_ClimateModeName[28:31]: ClimateModeDry,
	_ClimateModeName[31:35]: ClimateModeAuto,
}

// ParseClimateMode attempts to convert a string to a ClimateMode.
func ParseClimateMode(name string) (ClimateMode, error) {
	if x, ok := _ClimateModeValue[name]; ok {
		return x, nil
	}
	return ClimateMode(0), fmt.Errorf("%s is %w", name, ErrInvalidClimateMode)
}

const (
	// ClimatePresetNone is a ClimatePreset of type None.
	ClimatePresetNone ClimatePreset = iota
	// ClimatePresetHome is a ClimatePreset of type Home.
	ClimatePresetHome
	// ClimatePresetAway is a ClimatePreset of type Away.
	ClimatePresetAway
	// ClimatePresetBoost is a ClimatePreset of type Boost.
	ClimatePresetBoost
	// ClimatePresetComfort is a ClimatePreset of type Comfort.
	ClimatePresetComfort
	// ClimatePresetEco is a ClimatePreset of type Eco.
	ClimatePresetEco
	// ClimatePresetSleep is a ClimatePreset of type Sleep.
	ClimatePresetSleep
	// ClimatePresetActivity is a ClimatePreset of type Activity.
	ClimatePresetActivity
)

var ErrInvalidClimatePreset = errors.New("not a valid ClimatePreset")

const _ClimatePresetName = "nonehomeawayboostcomfortecosleepactivity"

var _ClimatePresetMap = map[ClimatePreset]string{
	ClimatePresetNone:     _ClimatePresetName[0:4],
	ClimatePresetHome:     _ClimatePresetName[4:8],
	ClimatePresetAway:     _ClimatePresetName[8:12],
	ClimatePresetBoost:    _ClimatePresetName[12:17],
	ClimatePresetComfort:  _ClimatePresetName[17:24],
	ClimatePresetEco:      _ClimatePresetName[24:27],
	ClimatePresetSleep:    _ClimatePresetName[27:32],
	ClimatePresetActivity: _ClimatePresetName[32:40],
}

// String implements the Stringer interface.
func (x ClimatePreset) String() string {
	if str, ok := _ClimatePresetMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ClimatePreset(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClimatePreset) IsValid() bool {
	_, ok := _ClimatePresetMap[x]
	return ok
}

var _ClimatePresetValue = map[string]ClimatePreset{
	_ClimatePresetName[0:4]:   ClimatePresetNone,
	_ClimatePresetName[4:8]:   ClimatePresetHome,
	_ClimatePresetName[8:12]:  ClimatePresetAway,
	_ClimatePresetName[12:17]: ClimatePresetBoost,
	_ClimatePresetName[17:24]: ClimatePresetComfort,
	_ClimatePresetName[24:27]: ClimatePresetEco,
	_ClimatePresetName[27:32]: ClimatePresetSleep,
	_ClimatePresetName[32:40]: ClimatePresetActivity,
}

// ParseClimatePreset attempts to convert a string to a ClimatePreset.
func ParseClimatePreset(name string) (ClimatePreset, error) {
	if x, ok := _ClimatePresetValue[name]; ok {
		return x, nil
	}
	return ClimatePreset(0), fmt.Errorf("%s is %w", name, ErrInvalidClimatePreset)
}

const (
	// ClimateSwingModeOff is a ClimateSwingMode of type Off.
	ClimateSwingModeOff ClimateSwingMode = iota
	// ClimateSwingModeBoth is a ClimateSwingMode of type Both.
	ClimateSwingModeBoth
	// ClimateSwingModeVertical is a ClimateSwingMode of type Vertical.
	ClimateSwingModeVertical
	// ClimateSwingModeHorizontal is a ClimateSwingMode of type Horizontal.
	ClimateSwingModeHorizontal
)

var ErrInvalidClimateSwingMode = errors.New("not a valid ClimateSwingMode")

const _ClimateSwingModeName = "offbothverticalhorizontal"

var _ClimateSwingModeMap = map[ClimateSwingMode]string{
	ClimateSwingModeOff:        _ClimateSwingModeName[0:3],
	ClimateSwingModeBoth:       _ClimateSwingModeName[3:7],
	ClimateSwingModeVertical:   _ClimateSwingModeName[7:15],
	ClimateSwingModeHorizontal: _ClimateSwingModeName[15:25],
}

// String implements the Stringer interface.
func (x ClimateSwingMode) String() string {
	if str, ok := _ClimateSwingModeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ClimateSwingMode(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClimateSwingMode) IsValid() bool {
	_, ok := _ClimateSwingModeMap[x]
	return ok
}

var _ClimateSwingModeValue = map[string]ClimateSwingMode{
	_ClimateSwingModeName[0:3]:   ClimateSwingModeOff,
	_ClimateSwingModeName[3:7]:   ClimateSwingModeBoth,
	_ClimateSwingModeName[7:15]:  ClimateSwingModeVertical,
	_ClimateSwingModeName[15:25]: ClimateSwingModeHorizontal,
}

// ParseClimateSwingMode attempts to convert a string to a ClimateSwingMode.
func ParseClimateSwingMode(name string) (ClimateSwingMode, error) {
	if x, ok := _ClimateSwingModeValue[name]; ok {
		return x, nil
	}
	return ClimateSwingMode(0), fmt.Errorf("%s is %w", name, ErrInvalidClimateSwingMode)
}

const (
	// DomainTypeBinarySensor is a DomainType of type Binary_sensor.
	DomainTypeBinarySensor DomainType = iota
	// DomainTypeCover is a DomainType of type Cover.
	DomainTypeCover
	// DomainTypeFan is a DomainType of type Fan.
	DomainTypeFan
	// DomainTypeLight is a DomainType of type Light.
	DomainTypeLight
	// DomainTypeSensor is a DomainType of type Sensor.
	DomainTypeSensor
	// DomainTypeSwitch is a DomainType of type Switch.
	DomainTypeSwitch
	// DomainTypeButton is a DomainType of type Button.
	DomainTypeButton
	// DomainTypeTextSensor is a DomainType of type Text_sensor.
	DomainTypeTextSensor
	// DomainTypeService is a DomainType of type Service.
	DomainTypeService
	// DomainTypeCamera is a DomainType of type Camera.
	DomainTypeCamera
	// DomainTypeClimate is a DomainType of type Climate.
	DomainTypeClimate
	// DomainTypeNumber is a DomainType of type Number.
	DomainTypeNumber
	// DomainTypeDatetimeDate is a DomainType of type Datetime_date.
	DomainTypeDatetimeDate
	// DomainTypeDatetimeTime is a DomainType of type Datetime_time.
	DomainTypeDatetimeTime
	// DomainTypeDatetimeDatetime is a DomainType of type Datetime_datetime.
	DomainTypeDatetimeDatetime
	// DomainTypeText is a DomainType of type Text.
	DomainTypeText
	// DomainTypeSelect is a DomainType of type Select.
	DomainTypeSelect
	// DomainTypeLock is a DomainType of type Lock.
	DomainTypeLock
	// DomainTypeValve is a DomainType of type Valve.
	DomainTypeValve
	// DomainTypeMediaPlayer is a DomainType of type Media_player.
	DomainTypeMediaPlayer
	// DomainTypeAlarmControlPanel is a DomainType of type Alarm_control_panel.
	DomainTypeAlarmControlPanel
	// DomainTypeEvent is a DomainType of type Event.
	DomainTypeEvent
	// DomainTypeUpdate is a DomainType of type Update.
	DomainTypeUpdate
)

var ErrInvalidDomainType = errors.New("not a valid DomainType")

const _DomainTypeName = "binary_sensorcoverfanlightsensorswitchbuttontext_sensorservicecameraclimatenumberdatetime_datedatetime_timedatetime_datetimetextselectlockvalvemedia_playeralarm_control_paneleventupdate"

var _DomainTypeMap = map[DomainType]string{
	DomainTypeBinarySensor:      _DomainTypeName[0:13],
	DomainTypeCover:             _DomainTypeName[13:18],
	DomainTypeFan:               _DomainTypeName[18:21],
	DomainTypeLight:             _DomainTypeName[21:26],
	DomainTypeSensor:            _DomainTypeName[26:32],
	DomainTypeSwitch:            _DomainTypeName[32:38],
	DomainTypeButton:            _DomainTypeName[38:44],
	DomainTypeTextSensor:        _DomainTypeName[44:55],
	DomainTypeService:           _DomainTypeName[55:62],
	DomainTypeCamera:            _DomainTypeName[62:68],
	DomainTypeClimate:           _DomainTypeName[68:75],
	DomainTypeNumber:            _DomainTypeName[75:81],
	DomainTypeDatetimeDate:      _DomainTypeName[81:94],
	DomainTypeDatetimeTime:      _DomainTypeName[94:107],
	DomainTypeDatetimeDatetime:  _DomainTypeName[107:124],
	DomainTypeText:              _DomainTypeName[124:128],
	DomainTypeSelect:            _DomainTypeName[128:134],
	DomainTypeLock:              _DomainTypeName[134:138],
	DomainTypeValve:             _DomainTypeName[138:143],
	DomainTypeMediaPlayer:       _DomainTypeName[143:155],
	DomainTypeAlarmControlPanel: _DomainTypeName[155:174],
	DomainTypeEvent:             _DomainTypeName[174:179],
	DomainTypeUpdate:            _DomainTypeName[179:185],
}

// String implements the Stringer interface.
func (x DomainType) String() string {
	if str, ok := _DomainTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("DomainType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DomainType) IsValid() bool {
	_, ok := _DomainTypeMap[x]
	return ok
}

var _DomainTypeValue = map[string]DomainType{
	_DomainTypeName[0:13]:    DomainTypeBinarySensor,
	_DomainTypeName[13:18]:   DomainTypeCover,
	_DomainTypeName[18:21]:   DomainTypeFan,
	_DomainTypeName[21:26]:   DomainTypeLight,
	_DomainTypeName[26:32]:   DomainTypeSensor,
	_DomainTypeName[32:38]:   DomainTypeSwitch,
	_DomainTypeName[38:44]:   DomainTypeButton,
	_DomainTypeName[44:55]:   DomainTypeTextSensor,
	_DomainTypeName[55:62]:   DomainTypeService,
	_DomainTypeName[62:68]:   DomainTypeCamera,
	_DomainTypeName[68:75]:   DomainTypeClimate,
	_DomainTypeName[75:81]:   DomainTypeNumber,
	_DomainTypeName[81:94]:   DomainTypeDatetimeDate,
	_DomainTypeName[94:107]:  DomainTypeDatetimeTime,
	_DomainTypeName[107:124]: DomainTypeDatetimeDatetime,
	_DomainTypeName[124:128]: DomainTypeText,
	_DomainTypeName[128:134]: DomainTypeSelect,
	_DomainTypeName[134:138]: DomainTypeLock,
	_DomainTypeName[138:143]: DomainTypeValve,
	_DomainTypeName[143:155]: DomainTypeMediaPlayer,
	_DomainTypeName[155:174]: DomainTypeAlarmControlPanel,
	_DomainTypeName[174:179]: DomainTypeEvent,
	_DomainTypeName[179:185]: DomainTypeUpdate,
}

// ParseDomainType attempts to convert a string to a DomainType.
func ParseDomainType(name string) (DomainType, error) {
	if x, ok := _DomainTypeValue[name]; ok {
		return x, nil
	}
	return DomainType(0), fmt.Errorf("%s is %w", name, ErrInvalidDomainType)
}

const (
	// FanDirectionForwardreverse is a FanDirection of type Forward.reverse.
	FanDirectionForwardreverse FanDirection = iota
)

var ErrInvalidFanDirection = errors.New("not a valid FanDirection")

const _FanDirectionName = "forward.reverse"

var _FanDirectionMap = map[FanDirection]string{
	FanDirectionForwardreverse: _FanDirectionName[0:15],
}

// String implements the Stringer interface.
func (x FanDirection) String() string {
	if str, ok := _FanDirectionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("FanDirection(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FanDirection) IsValid() bool {
	_, ok := _FanDirectionMap[x]
	return ok
}

var _FanDirectionValue = map[string]FanDirection{
	_FanDirectionName[0:15]: FanDirectionForwardreverse,
}

// ParseFanDirection attempts to convert a string to a FanDirection.
func ParseFanDirection(name string) (FanDirection, error) {
	if x, ok := _FanDirectionValue[name]; ok {
		return x, nil
	}
	return FanDirection(0), fmt.Errorf("%s is %w", name, ErrInvalidFanDirection)
}

const (
	// FanSpeedLow is a FanSpeed of type Low.
	FanSpeedLow FanSpeed = iota
	// FanSpeedMedium is a FanSpeed of type Medium.
	FanSpeedMedium
	// FanSpeedHigh is a FanSpeed of type High.
	FanSpeedHigh
)

var ErrInvalidFanSpeed = errors.New("not a valid FanSpeed")

const _FanSpeedName = "lowmediumhigh"

var _FanSpeedMap = map[FanSpeed]string{
	FanSpeedLow:    _FanSpeedName[0:3],
	FanSpeedMedium: _FanSpeedName[3:9],
	FanSpeedHigh:   _FanSpeedName[9:13],
}

// String implements the Stringer interface.
func (x FanSpeed) String() string {
	if str, ok := _FanSpeedMap[x]; ok {
		return str
	}
	return fmt.Sprintf("FanSpeed(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FanSpeed) IsValid() bool {
	_, ok := _FanSpeedMap[x]
	return ok
}

var _FanSpeedValue = map[string]FanSpeed{
	_FanSpeedName[0:3]:  FanSpeedLow,
	_FanSpeedName[3:9]:  FanSpeedMedium,
	_FanSpeedName[9:13]: FanSpeedHigh,
}

// ParseFanSpeed attempts to convert a string to a FanSpeed.
func ParseFanSpeed(name string) (FanSpeed, error) {
	if x, ok := _FanSpeedValue[name]; ok {
		return x, nil
	}
	return FanSpeed(0), fmt.Errorf("%s is %w", name, ErrInvalidFanSpeed)
}

const (
	// LegacyCoverStateOpen is a LegacyCoverState of type Open.
	LegacyCoverStateOpen LegacyCoverState = iota
	// LegacyCoverStateClosed is a LegacyCoverState of type Closed.
	LegacyCoverStateClosed
)

var ErrInvalidLegacyCoverState = errors.New("not a valid LegacyCoverState")

const _LegacyCoverStateName = "openclosed"

var _LegacyCoverStateMap = map[LegacyCoverState]string{
	LegacyCoverStateOpen:   _LegacyCoverStateName[0:4],
	LegacyCoverStateClosed: _LegacyCoverStateName[4:10],
}

// String implements the Stringer interface.
func (x LegacyCoverState) String() string {
	if str, ok := _LegacyCoverStateMap[x]; ok {
		return str
	}
	return fmt.Sprintf("LegacyCoverState(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x LegacyCoverState) IsValid() bool {
	_, ok := _LegacyCoverStateMap[x]
	return ok
}

var _LegacyCoverStateValue = map[string]LegacyCoverState{
	_LegacyCoverStateName[0:4]:  LegacyCoverStateOpen,
	_LegacyCoverStateName[4:10]: LegacyCoverStateClosed,
}

// ParseLegacyCoverState attempts to convert a string to a LegacyCoverState.
func ParseLegacyCoverState(name string) (LegacyCoverState, error) {
	if x, ok := _LegacyCoverStateValue[name]; ok {
		return x, nil
	}
	return LegacyCoverState(0), fmt.Errorf("%s is %w", name, ErrInvalidLegacyCoverState)
}

const (
	// LockStateNone is a LockState of type None.
	LockStateNone LockState = iota
	// LockStateLocked is a LockState of type Locked.
	LockStateLocked
	// LockStateUnlocked is a LockState of type Unlocked.
	LockStateUnlocked
	// LockStateJammed is a LockState of type Jammed.
	LockStateJammed
	// LockStateLocking is a LockState of type Locking.
	LockStateLocking
	// LockStateUnlocking is a LockState of type Unlocking.
	LockStateUnlocking
)

var ErrInvalidLockState = errors.New("not a valid LockState")

const _LockStateName = "nonelockedunlockedjammedlockingunlocking"

var _LockStateMap = map[LockState]string{
	LockStateNone:      _LockStateName[0:4],
	LockStateLocked:    _LockStateName[4:10],
	LockStateUnlocked:  _LockStateName[10:18],
	LockStateJammed:    _LockStateName[18:24],
	LockStateLocking:   _LockStateName[24:31],
	LockStateUnlocking: _LockStateName[31:40],
}

// String implements the Stringer interface.
func (x LockState) String() string {
	if str, ok := _LockStateMap[x]; ok {
		return str
	}
	return fmt.Sprintf("LockState(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x LockState) IsValid() bool {
	_, ok := _LockStateMap[x]
	return ok
}

var _LockStateValue = map[string]LockState{
	_LockStateName[0:4]:   LockStateNone,
	_LockStateName[4:10]:  LockStateLocked,
	_LockStateName[10:18]: LockStateUnlocked,
	_LockStateName[18:24]: LockStateJammed,
	_LockStateName[24:31]: LockStateLocking,
	_LockStateName[31:40]: LockStateUnlocking,
}

// ParseLockState attempts to convert a string to a LockState.
func ParseLockState(name string) (LockState, error) {
	if x, ok := _LockStateValue[name]; ok {
		return x, nil
	}
	return LockState(0), fmt.Errorf("%s is %w", name, ErrInvalidLockState)
}

const (
	// MediaPlayingStateNone is a MediaPlayingState of type None.
	MediaPlayingStateNone MediaPlayingState = iota
	// MediaPlayingStateIdle is a MediaPlayingState of type Idle.
	MediaPlayingStateIdle
	// MediaPlayingStatePlaying is a MediaPlayingState of type Playing.
	MediaPlayingStatePlaying
	// MediaPlayingStatePaused is a MediaPlayingState of type Paused.
	MediaPlayingStatePaused
)

var ErrInvalidMediaPlayingState = errors.New("not a valid MediaPlayingState")

const _MediaPlayingStateName = "noneidleplayingpaused"

var _MediaPlayingStateMap = map[MediaPlayingState]string{
	MediaPlayingStateNone:    _MediaPlayingStateName[0:4],
	MediaPlayingStateIdle:    _MediaPlayingStateName[4:8],
	MediaPlayingStatePlaying: _MediaPlayingStateName[8:15],
	MediaPlayingStatePaused:  _MediaPlayingStateName[15:21],
}

// String implements the Stringer interface.
func (x MediaPlayingState) String() string {
	if str, ok := _MediaPlayingStateMap[x]; ok {
		return str
	}
	return fmt.Sprintf("MediaPlayingState(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MediaPlayingState) IsValid() bool {
	_, ok := _MediaPlayingStateMap[x]
	return ok
}

var _MediaPlayingStateValue = map[string]MediaPlayingState{
	_MediaPlayingStateName[0:4]:   MediaPlayingStateNone,
	_MediaPlayingStateName[4:8]:   MediaPlayingStateIdle,
	_MediaPlayingStateName[8:15]:  MediaPlayingStatePlaying,
	_MediaPlayingStateName[15:21]: MediaPlayingStatePaused,
}

// ParseMediaPlayingState attempts to convert a string to a MediaPlayingState.
func ParseMediaPlayingState(name string) (MediaPlayingState, error) {
	if x, ok := _MediaPlayingStateValue[name]; ok {
		return x, nil
	}
	return MediaPlayingState(0), fmt.Errorf("%s is %w", name, ErrInvalidMediaPlayingState)
}

const (
	// ValveOperationIdle is a ValveOperation of type Idle.
	ValveOperationIdle ValveOperation = iota
	// ValveOperationIsOpening is a ValveOperation of type Is_opening.
	ValveOperationIsOpening
	// ValveOperationIsClosing is a ValveOperation of type Is_closing.
	ValveOperationIsClosing
)

var ErrInvalidValveOperation = errors.New("not a valid ValveOperation")

const _ValveOperationName = "idleis_openingis_closing"

var _ValveOperationMap = map[ValveOperation]string{
	ValveOperationIdle:      _ValveOperationName[0:4],
	ValveOperationIsOpening: _ValveOperationName[4:14],
	ValveOperationIsClosing: _ValveOperationName[14:24],
}

// String implements the Stringer interface.
func (x ValveOperation) String() string {
	if str, ok := _ValveOperationMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ValveOperation(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ValveOperation) IsValid() bool {
	_, ok := _ValveOperationMap[x]
	return ok
}

var _ValveOperationValue = map[string]ValveOperation{
	_ValveOperationName[0:4]:   ValveOperationIdle,
	_ValveOperationName[4:14]:  ValveOperationIsOpening,
	_ValveOperationName[14:24]: ValveOperationIsClosing,
}

// ParseValveOperation attempts to convert a string to a ValveOperation.
func ParseValveOperation(name string) (ValveOperation, error) {
	if x, ok := _ValveOperationValue[name]; ok {
		return x, nil
	}
	return ValveOperation(0), fmt.Errorf("%s is %w", name, ErrInvalidValveOperation)
}
