// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package entity

import (
	"errors"
	"fmt"
)

const (
	// EntityCategoryNone is a EntityCategory of type None.
	EntityCategoryNone EntityCategory = iota
	// EntityCategoryConfig is a EntityCategory of type Config.
	EntityCategoryConfig
	// EntityCategoryDisgnostic is a EntityCategory of type Disgnostic.
	EntityCategoryDisgnostic
)

var ErrInvalidEntityCategory = errors.New("not a valid EntityCategory")

const _EntityCategoryName = "noneconfigdisgnostic"

var _EntityCategoryMap = map[EntityCategory]string{
	EntityCategoryNone:       _EntityCategoryName[0:4],
	EntityCategoryConfig:     _EntityCategoryName[4:10],
	EntityCategoryDisgnostic: _EntityCategoryName[10:20],
}

// String implements the Stringer interface.
func (x EntityCategory) String() string {
	if str, ok := _EntityCategoryMap[x]; ok {
		return str
	}
	return fmt.Sprintf("EntityCategory(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EntityCategory) IsValid() bool {
	_, ok := _EntityCategoryMap[x]
	return ok
}

var _EntityCategoryValue = map[string]EntityCategory{
	_EntityCategoryName[0:4]:   EntityCategoryNone,
	_EntityCategoryName[4:10]:  EntityCategoryConfig,
	_EntityCategoryName[10:20]: EntityCategoryDisgnostic,
}

// ParseEntityCategory attempts to convert a string to a EntityCategory.
func ParseEntityCategory(name string) (EntityCategory, error) {
	if x, ok := _EntityCategoryValue[name]; ok {
		return x, nil
	}
	return EntityCategory(0), fmt.Errorf("%s is %w", name, ErrInvalidEntityCategory)
}

// MarshalText implements the text marshaller method.
func (x EntityCategory) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EntityCategory) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseEntityCategory(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
