// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package button

import (
	"fmt"
	"strings"
)

const (
	// DeviceClassIdentify is a DeviceClass of type identify.
	// The button is used to identify a device.
	DeviceClassIdentify DeviceClass = "identify"
	// DeviceClassRestart is a DeviceClass of type restart.
	// The button restarts the device.
	DeviceClassRestart DeviceClass = "restart"
	// DeviceClassUpdate is a DeviceClass of type update.
	// The button updates the software of the device.
	DeviceClassUpdate DeviceClass = "update"
)

var ErrInvalidDeviceClass = fmt.Errorf("not a valid DeviceClass, try [%s]", strings.Join(_DeviceClassNames, ", "))

var _DeviceClassNames = []string{
	string(DeviceClassIdentify),
	string(DeviceClassRestart),
	string(DeviceClassUpdate),
}

// DeviceClassNames returns a list of possible string values of DeviceClass.
func DeviceClassNames() []string {
	tmp := make([]string, len(_DeviceClassNames))
	copy(tmp, _DeviceClassNames)
	return tmp
}

// DeviceClassValues returns a list of the values for DeviceClass
func DeviceClassValues() []DeviceClass {
	return []DeviceClass{
		DeviceClassIdentify,
		DeviceClassRestart,
		DeviceClassUpdate,
	}
}

// String implements the Stringer interface.
func (x DeviceClass) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DeviceClass) IsValid() bool {
	_, err := ParseDeviceClass(string(x))
	return err == nil
}

var _DeviceClassValue = map[string]DeviceClass{
	"identify": DeviceClassIdentify,
	"restart":  DeviceClassRestart,
	"update":   DeviceClassUpdate,
}

// ParseDeviceClass attempts to convert a string to a DeviceClass.
func ParseDeviceClass(name string) (DeviceClass, error) {
	if x, ok := _DeviceClassValue[name]; ok {
		return x, nil
	}
	return DeviceClass(""), fmt.Errorf("%s is %w", name, ErrInvalidDeviceClass)
}
