// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package binarysensor

import (
	"fmt"
	"strings"
)

const (
	// DeviceClassBattery is a DeviceClass of type battery.
	DeviceClassBattery DeviceClass = "battery"
	// DeviceClassBatteryCharging is a DeviceClass of type battery_charging.
	DeviceClassBatteryCharging DeviceClass = "battery_charging"
	// DeviceClassCarbonMonoxide is a DeviceClass of type carbon_monoxide.
	DeviceClassCarbonMonoxide DeviceClass = "carbon_monoxide"
	// DeviceClassCold is a DeviceClass of type cold.
	DeviceClassCold DeviceClass = "cold"
	// DeviceClassConnectivity is a DeviceClass of type connectivity.
	DeviceClassConnectivity DeviceClass = "connectivity"
	// DeviceClassDoor is a DeviceClass of type door.
	DeviceClassDoor DeviceClass = "door"
	// DeviceClassEmpty is a DeviceClass of type empty.
	DeviceClassEmpty DeviceClass = "empty"
	// DeviceClassGarageDoor is a DeviceClass of type garage_door.
	DeviceClassGarageDoor DeviceClass = "garage_door"
	// DeviceClassGas is a DeviceClass of type gas.
	DeviceClassGas DeviceClass = "gas"
	// DeviceClassHeat is a DeviceClass of type heat.
	DeviceClassHeat DeviceClass = "heat"
	// DeviceClassLight is a DeviceClass of type light.
	DeviceClassLight DeviceClass = "light"
	// DeviceClassLock is a DeviceClass of type lock.
	DeviceClassLock DeviceClass = "lock"
	// DeviceClassMoisture is a DeviceClass of type moisture.
	DeviceClassMoisture DeviceClass = "moisture"
	// DeviceClassMotion is a DeviceClass of type motion.
	DeviceClassMotion DeviceClass = "motion"
	// DeviceClassMoving is a DeviceClass of type moving.
	DeviceClassMoving DeviceClass = "moving"
	// DeviceClassOccupancy is a DeviceClass of type occupancy.
	DeviceClassOccupancy DeviceClass = "occupancy"
	// DeviceClassOpening is a DeviceClass of type opening.
	DeviceClassOpening DeviceClass = "opening"
	// DeviceClassPlug is a DeviceClass of type plug.
	DeviceClassPlug DeviceClass = "plug"
	// DeviceClassPower is a DeviceClass of type power.
	DeviceClassPower DeviceClass = "power"
	// DeviceClassPresence is a DeviceClass of type presence.
	DeviceClassPresence DeviceClass = "presence"
	// DeviceClassProblem is a DeviceClass of type problem.
	DeviceClassProblem DeviceClass = "problem"
	// DeviceClassRunning is a DeviceClass of type running.
	DeviceClassRunning DeviceClass = "running"
	// DeviceClassSafety is a DeviceClass of type safety.
	DeviceClassSafety DeviceClass = "safety"
	// DeviceClassSmoke is a DeviceClass of type smoke.
	DeviceClassSmoke DeviceClass = "smoke"
	// DeviceClassSound is a DeviceClass of type sound.
	DeviceClassSound DeviceClass = "sound"
	// DeviceClassTamper is a DeviceClass of type tamper.
	DeviceClassTamper DeviceClass = "tamper"
	// DeviceClassUpdate is a DeviceClass of type update.
	DeviceClassUpdate DeviceClass = "update"
	// DeviceClassVibration is a DeviceClass of type vibration.
	DeviceClassVibration DeviceClass = "vibration"
	// DeviceClassWindow is a DeviceClass of type window.
	DeviceClassWindow DeviceClass = "window"
)

var ErrInvalidDeviceClass = fmt.Errorf("not a valid DeviceClass, try [%s]", strings.Join(_DeviceClassNames, ", "))

var _DeviceClassNames = []string{
	string(DeviceClassBattery),
	string(DeviceClassBatteryCharging),
	string(DeviceClassCarbonMonoxide),
	string(DeviceClassCold),
	string(DeviceClassConnectivity),
	string(DeviceClassDoor),
	string(DeviceClassEmpty),
	string(DeviceClassGarageDoor),
	string(DeviceClassGas),
	string(DeviceClassHeat),
	string(DeviceClassLight),
	string(DeviceClassLock),
	string(DeviceClassMoisture),
	string(DeviceClassMotion),
	string(DeviceClassMoving),
	string(DeviceClassOccupancy),
	string(DeviceClassOpening),
	string(DeviceClassPlug),
	string(DeviceClassPower),
	string(DeviceClassPresence),
	string(DeviceClassProblem),
	string(DeviceClassRunning),
	string(DeviceClassSafety),
	string(DeviceClassSmoke),
	string(DeviceClassSound),
	string(DeviceClassTamper),
	string(DeviceClassUpdate),
	string(DeviceClassVibration),
	string(DeviceClassWindow),
}

// DeviceClassNames returns a list of possible string values of DeviceClass.
func DeviceClassNames() []string {
	tmp := make([]string, len(_DeviceClassNames))
	copy(tmp, _DeviceClassNames)
	return tmp
}

// DeviceClassValues returns a list of the values for DeviceClass
func DeviceClassValues() []DeviceClass {
	return []DeviceClass{
		DeviceClassBattery,
		DeviceClassBatteryCharging,
		DeviceClassCarbonMonoxide,
		DeviceClassCold,
		DeviceClassConnectivity,
		DeviceClassDoor,
		DeviceClassEmpty,
		DeviceClassGarageDoor,
		DeviceClassGas,
		DeviceClassHeat,
		DeviceClassLight,
		DeviceClassLock,
		DeviceClassMoisture,
		DeviceClassMotion,
		DeviceClassMoving,
		DeviceClassOccupancy,
		DeviceClassOpening,
		DeviceClassPlug,
		DeviceClassPower,
		DeviceClassPresence,
		DeviceClassProblem,
		DeviceClassRunning,
		DeviceClassSafety,
		DeviceClassSmoke,
		DeviceClassSound,
		DeviceClassTamper,
		DeviceClassUpdate,
		DeviceClassVibration,
		DeviceClassWindow,
	}
}

// String implements the Stringer interface.
func (x DeviceClass) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DeviceClass) IsValid() bool {
	_, err := ParseDeviceClass(string(x))
	return err == nil
}

var _DeviceClassValue = map[string]DeviceClass{
	"battery":          DeviceClassBattery,
	"battery_charging": DeviceClassBatteryCharging,
	"carbon_monoxide":  DeviceClassCarbonMonoxide,
	"cold":             DeviceClassCold,
	"connectivity":     DeviceClassConnectivity,
	"door":             DeviceClassDoor,
	"empty":            DeviceClassEmpty,
	"garage_door":      DeviceClassGarageDoor,
	"gas":              DeviceClassGas,
	"heat":             DeviceClassHeat,
	"light":            DeviceClassLight,
	"lock":             DeviceClassLock,
	"moisture":         DeviceClassMoisture,
	"motion":           DeviceClassMotion,
	"moving":           DeviceClassMoving,
	"occupancy":        DeviceClassOccupancy,
	"opening":          DeviceClassOpening,
	"plug":             DeviceClassPlug,
	"power":            DeviceClassPower,
	"presence":         DeviceClassPresence,
	"problem":          DeviceClassProblem,
	"running":          DeviceClassRunning,
	"safety":           DeviceClassSafety,
	"smoke":            DeviceClassSmoke,
	"sound":            DeviceClassSound,
	"tamper":           DeviceClassTamper,
	"update":           DeviceClassUpdate,
	"vibration":        DeviceClassVibration,
	"window":           DeviceClassWindow,
}

// ParseDeviceClass attempts to convert a string to a DeviceClass.
func ParseDeviceClass(name string) (DeviceClass, error) {
	if x, ok := _DeviceClassValue[name]; ok {
		return x, nil
	}
	return DeviceClass(""), fmt.Errorf("%s is %w", name, ErrInvalidDeviceClass)
}
